apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: erik
spec:
  selector:
    role: api
  ports:
    - protocol: TCP
      port: 80           # Port to access outside the cluster
      targetPort: 8080    # Port the API container is listening on
      nodePort: 30181     # Port on each node to access the service
  type: NodePort
